### ISSUE TITLE
Formatting for Caso de Uso Zotero in tropy-es.md

### ISSUE THREAD

**Issue by mcraed2004** [spapastamkou/tropy-tutorial#2]
After Line 217, instructions for Zotero integration should be in outline formatting, but markdown conversion renders it as a long list of steps [tropy-es.md](https://github.com/spapastamkou/tropy-tutorial/blob/main/lesson/tropy-es.md)

See formatting in Google Doc edition
https://docs.google.com/document/d/1YEFP-8qlmB9UDMRUtt2-WBfzqlnIpdG1BDtp8AZeKvM/edit

**Comment by spapastamkou** [comment]
I think [it is ok now](https://github.com/spapastamkou/tropy-tutorial/commit/56773d589884aab6f5f703ef50e24ffdec92f7bd) - but if you have further suggestions, let me know. There was a lot of indentation and tried to define the levels a bit differently. We can modify again if necessary.
